ros2_kdl_node:
  ros__parameters:
    cmd_interface: "velocity"
    vel_prof: "cubic"
    trajectory: "linear"
    Kpp: 0.05
    Kdd: 0.05
    Kp: 1.0
    Kd: 1.0
    Kpp_o: 25.0
    Kpo_o: 25.0
    Kdp_o: 10.0 
    Kdo_o: 10.0

ros2_kdl_vision:
  ros__parameters:
    cmd_interface: "velocity"
    vel_prof: "cubic"
    trajectory: "linear"
    task: "positioning"
    Kpp: 1.2
    Kdd: 0.1
    Kp: 1.0
    Kd: 1.0
    Kpp_o: 25.0
    Kpo_o: 25.0
    Kdp_o: 5.0 
    Kdo_o: 5.0
    x_offset: 0.5
    y_offset: 0.3
    z_offset: 0.0
    roll_offset: 0.0
    pitch_offset: 0.0
    yaw_offset: 0.0
